language: php
php:
  - 5.4
  - 5.5
  - 5.6
sudo: required
addons:
  apt:
    packages:
    - php5-cli
    - php5-xmlrpc
before_install:
    - php5 /home/travis/.phpenv/versions/5.5/bin/composer self-update

